---

apiVersion: v1
kind: Service
metadata:
  name: nginx-sample
  labels:
    app: nginx-sample
spec:
  ports:
  - port: 4011
    targetPort: 80
    protocol: TCP
    name: http
  type: NodePort
  selector:
    app: nginx-sample
